services:
  - type: web
    name: nutrition-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
    ports:
      - port: 5000
        protocol: HTTP