services:
  - type: web
    name: nutrition-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false

  - type: web
    name: health-check
    env: python
    plan: free
    buildCommand: pip install flask
    startCommand: python health_check.py
    envVars:
      - key: PORT
        value: 5000